// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	randm "github.com/hsuanshao/go-tools/randm"
	mock "github.com/stretchr/testify/mock"
)

// Method is an autogenerated mock type for the Method type
type Method struct {
	mock.Mock
}

// GenRandomString provides a mock function with given fields: length
func (_m *Method) GenRandomString(length uint) string {
	ret := _m.Called(length)

	var r0 string
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GenerateRID provides a mock function with given fields:
func (_m *Method) GenerateRID() randm.RID {
	ret := _m.Called()

	var r0 randm.RID
	if rf, ok := ret.Get(0).(func() randm.RID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(randm.RID)
	}

	return r0
}

// IsValidateRID provides a mock function with given fields: rid
func (_m *Method) IsValidateRID(rid int64) bool {
	ret := _m.Called(rid)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = rf(rid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewMethod interface {
	mock.TestingT
	Cleanup(func())
}

// NewMethod creates a new instance of Method. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMethod(t mockConstructorTestingTNewMethod) *Method {
	mock := &Method{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
